# Loon 脚本订阅
# 建议订阅地址: https://raw.githubusercontent.com/lunanfo/Task/main/Scripts/imdb_lookup_script.conf

# [Script]
# manual 类型用于在 Loon 的“脚本”页面手动点击运行
# 您可以在引号中修改搜索关键词： "剧名 @ 年份"
cron "0 0 * 12 *"  script-path=https://raw.githubusercontent.com/lunanfo/Task/main/Scripts/imdb_lookup.js, tag=IMDb ID 查询, timeout=60, argument="The Last of Us @ 2023"
